import { create } from "zustand";
import p1 from "../assets/propertyAssets/p1.jpeg";
import p2 from "../assets/propertyAssets/p2.jpeg";
import p3 from "../assets/propertyAssets/p3.jpeg";
import p4 from "../assets/propertyAssets/p4.jpeg";
import p5 from "../assets/propertyAssets/p5.jpeg";
import p6 from "../assets/propertyDetail/detail4.jpg";
import p7 from "../assets/propertyDetail/detail5.jpg";
import p8 from "../assets/propertyDetail/detail6.jpg";
import p9 from "../assets/propertyDetail/detail7.jpg";
import p10 from "../assets/propertyDetail/detail9.jpg";
const condos = [
  {
    id: "AA123456",
    name: "Golden Pearl Condo",
    slug: "golden-pearl-condo",
    available: true,
    type: "rent",
    propertyImg: p1,
    shortDescription:
      "Prime condo located in downtown, just 10 minutes to the mall. Surrounded by lush parks, trendy cafes, and vibrant markets.",
    pricePerMonth: 1500,
    bedrooms: 2,
    bathrooms: 2,
    sizeSqft: 1200,
    listedDate: "2024-11-15",
    details: {
      description:
        "A beautifully designed condo with a modern layout, spacious living room, and fully equipped kitchen. Located in a prime downtown area with easy access to shopping centers and parks.",
      detailImg: [
        "/images/details/golden_pearl_condo_1.jpg",
        "/images/details/golden_pearl_condo_2.jpg",
        "/images/details/golden_pearl_condo_3.jpg",
      ],
      thumbnails: [
        "/images/details/thumbnails/golden_pearl_condo_1.jpg",
        "/images/details/thumbnails/golden_pearl_condo_2.jpg",
        "/images/details/thumbnails/golden_pearl_condo_3.jpg",
      ],
      propertyDetails: [
        ["Unit ID", "AA123456"],
        ["Property Type", "Condo"],
        ["Property Size", 1200],
        ["Rooms", 5],
        ["Bed Rooms", 2],
        ["Price", "$ 505,500.00 1000/per sq ft"],
        ["Property Status", "rent"],
        ["Lot Size", 0],
        ["Bath Rooms", 2],
        ["Garages", 1],
      ],
      amenitiesFeatures: [
        "Smoke Alarm",
        "Gym",
        "Parking",
        "24th Security",
        "Garden",
        "Swimming Pool",
        "WiFi",
        "Mini Playground",
        "Convenience store",
        "Laundry Shop",
      ],
      mapLocation: {
        latitude: 13.736717,
        longitude: 100.523186,
      },
    },
  },

  {
    id: "AA123457",
    name: "Emerald Bay Condo",
    slug: "emerald-bay-condo",
    available: true,
    type: "rent",
    propertyImg: p2,
    shortDescription:
      "Luxury condo with stunning bay views, gym access, and rooftop pool. Ideal for a contemporary lifestyle.",
    pricePerMonth: 1800,
    bedrooms: 3,
    bathrooms: 2,
    sizeSqft: 1500,
    listedDate: "2024-11-20",
    details: {
      description:
        "An elegant condo featuring open concept living, a modern kitchen, and a spacious balcony overlooking the bay. Close to restaurants and public transport.",
      detailImg: [
        "/images/details/emerald_bay_condo_1.jpg",
        "/images/details/emerald_bay_condo_2.jpg",
        "/images/details/emerald_bay_condo_3.jpg",
      ],
      thumbnails: [
        "/images/details/thumbnails/emerald_bay_condo_1.jpg",
        "/images/details/thumbnails/emerald_bay_condo_2.jpg",
        "/images/details/thumbnails/emerald_bay_condo_3.jpg",
      ],
      propertyDetails: [
        ["Unit ID", "AA123457"],
        ["Property Type", "Condo"],
        ["Property Size", 1500],
        ["Rooms", 6],
        ["Bed Rooms", 3],
        ["Price", "$ 615,000.00 1200/per sq ft"],
        ["Property Status", "rent"],
        ["Lot Size", 0],
        ["Bath Rooms", 2],
        ["Garages", 2],
      ],
      amenitiesFeatures: [
        "Swimming Pool",
        "Gym",
        "Parking",
        "Rooftop access",
        "Playground",
        "WiFi",
        "BBQ area",
        "Convenience store",
        "Laundry Shop",
      ],
      mapLocation: {
        latitude: 13.740717,
        longitude: 100.523186,
      },
    },
  },
  {
    id: "AA123458",
    name: "Sunny Vista Condo",
    slug: "sunny-vista-condo",
    available: true,
    type: "sale",
    propertyImg: p3,
    shortDescription:
      "Bright and airy condo in a quiet neighborhood, perfect for families and pets.",
    pricePerMonth: 2000,
    bedrooms: 4,
    bathrooms: 3,
    sizeSqft: 1800,
    listedDate: "2024-11-25",
    details: {
      description:
        "A spacious condo with plenty of natural light, modern kitchen amenities, and a large terrace. Family-friendly area with parks and schools nearby.",
      detailImg: [
        "/images/details/sunny_vista_condo_1.jpg",
        "/images/details/sunny_vista_condo_2.jpg",
        "/images/details/sunny_vista_condo_3.jpg",
      ],
      thumbnails: [
        "/images/details/thumbnails/sunny_vista_condo_1.jpg",
        "/images/details/thumbnails/sunny_vista_condo_2.jpg",
        "/images/details/thumbnails/sunny_vista_condo_3.jpg",
      ],
      propertyDetails: [
        ["Unit ID", "AA123458"],
        ["Property Type", "Condo"],
        ["Property Size", 1800],
        ["Rooms", 7],
        ["Bed Rooms", 4],
        ["Price", "$ 720,000.00 1300/per sq ft"],
        ["Property Status", "sale"],
        ["Lot Size", 0],
        ["Bath Rooms", 3],
        ["Garages", 2],
      ],
      amenitiesFeatures: [
        "Smoke Alarm",
        "Garden",
        "Garage",
        "Tennis Court",
        "Swimming Pool",
        "Playground",
        "WiFi",
        "Laundry Shop",
      ],
      mapLocation: {
        latitude: 13.745717,
        longitude: 100.520186,
      },
    },
  },
  {
    id: "AA123459",
    name: "Skyline Heights Condo",
    slug: "skyline-heights-condo",
    available: false,
    type: "rent",
    propertyImg: p4,
    shortDescription:
      "Luxurious living with unparalleled city views, high-end finishes, and exclusive amenities.",
    pricePerMonth: 2500,
    bedrooms: 2,
    bathrooms: 2,
    sizeSqft: 1600,
    listedDate: "2024-11-28",
    details: {
      description:
        "A luxury condo featuring floor-to-ceiling windows, a chef's kitchen, and access to a private rooftop terrace. Close to downtown attractions and nightlife.",
      detailImg: [
        "/images/details/skyline_heights_condo_1.jpg",
        "/images/details/skyline_heights_condo_2.jpg",
        "/images/details/skyline_heights_condo_3.jpg",
      ],
      thumbnails: [
        "/images/details/thumbnails/skyline_heights_condo_1.jpg",
        "/images/details/thumbnails/skyline_heights_condo_2.jpg",
        "/images/details/thumbnails/skyline_heights_condo_3.jpg",
      ],
      propertyDetails: [
        ["Unit ID", "AA123459"],
        ["Property Type", "Condo"],
        ["Property Size", 1600],
        ["Rooms", 4],
        ["Bed Rooms", 2],
        ["Price", "$ 500,000.00 1500/per sq ft"],
        ["Property Status", "rent"],
        ["Lot Size", 0],
        ["Bath Rooms", 2],
        ["Garages", 1],
      ],
      amenitiesFeatures: [
        "Exclusive Rooftop",
        "Gym",
        "Pool",
        "24/7 Security",
        "Parking",
        "Pet Friendly",
        "Smart Home Features",
        "Concierge Service",
      ],
      mapLocation: {
        latitude: 13.750717,
        longitude: 100.523186,
      },
    },
  },
  {
    id: "AA123460",
    name: "Ocean Breeze Condo",
    slug: "ocean-breeze-condo",
    available: true,
    type: "sale",
    propertyImg: p5,
    shortDescription:
      "Beachfront condo with stunning ocean views and direct beach access. Perfect for vacationers.",
    pricePerMonth: 3000,
    bedrooms: 3,
    bathrooms: 3,
    sizeSqft: 1750,
    listedDate: "2024-11-30",
    details: {
      description:
        "Experience coastal living in this beautiful condo with modern amenities, a private balcony, and large windows. Located near popular beach destinations.",
      detailImg: [
        "/images/details/ocean_breeze_condo_1.jpg",
        "/images/details/ocean_breeze_condo_2.jpg",
        "/images/details/ocean_breeze_condo_3.jpg",
      ],
      thumbnails: [
        "/images/details/thumbnails/ocean_breeze_condo_1.jpg",
        "/images/details/thumbnails/ocean_breeze_condo_2.jpg",
        "/images/details/thumbnails/ocean_breeze_condo_3.jpg",
      ],
      propertyDetails: [
        ["Unit ID", "AA123460"],
        ["Property Type", "Condo"],
        ["Property Size", 1750],
        ["Rooms", 6],
        ["Bed Rooms", 3],
        ["Price", "$ 825,000.00 4500/per sq ft"],
        ["Property Status", "sale"],
        ["Lot Size", 0],
        ["Bath Rooms", 3],
        ["Garages", 2],
      ],
      amenitiesFeatures: [
        "Private Beach Access",
        "Swimming Pool",
        "Gym",
        "BBQ Grill",
        "Parking",
        "WiFi",
        "Pet Friendly",
        "Tennis Court",
      ],
      mapLocation: {
        latitude: 13.7,
        longitude: 100.55,
      },
    },
  },
  {
    id: "AA123461",
    name: "Hilltop Retreat Condo",
    slug: "hilltop-retreat-condo",
    available: true,
    type: "rent",
    propertyImg: p6,
    shortDescription:
      "Spacious condo on a hilltop, offering panoramic views of the mountains and city.",
    pricePerMonth: 2100,
    bedrooms: 3,
    bathrooms: 2,
    sizeSqft: 1450,
    listedDate: "2024-12-01",
    details: {
      description:
        "A beautiful condo featuring large windows for natural light, modern amenities, and a cozy balcony. Located in a tranquil neighborhood perfect for relaxation.",
      detailImg: [
        "/images/details/hilltop_retreat_condo_1.jpg",
        "/images/details/hilltop_retreat_condo_2.jpg",
        "/images/details/hilltop_retreat_condo_3.jpg",
      ],
      thumbnails: [
        "/images/details/thumbnails/hilltop_retreat_condo_1.jpg",
        "/images/details/thumbnails/hilltop_retreat_condo_2.jpg",
        "/images/details/thumbnails/hilltop_retreat_condo_3.jpg",
      ],
      propertyDetails: [
        ["Unit ID", "AA123461"],
        ["Property Type", "Condo"],
        ["Property Size", 1450],
        ["Rooms", 5],
        ["Bed Rooms", 3],
        ["Price", "$ 682,500.00 1500/per sq ft"],
        ["Property Status", "rent"],
        ["Lot Size", 0],
        ["Bath Rooms", 2],
        ["Garages", 1],
      ],
      amenitiesFeatures: [
        "Mountain View",
        "Gym",
        "Parking",
        "Swimming Pool",
        "24/7 Security",
        "Garden",
        "WiFi",
        "Laundry Service",
      ],
      mapLocation: {
        latitude: 13.78,
        longitude: 100.52,
      },
    },
  },
  {
    id: "AA123462",
    name: "Urban Living Condo",
    slug: "urban-living-condo",
    available: true,
    type: "rent",
    propertyImg: p7,
    shortDescription:
      "Modern condo in the heart of the city, surrounded by shops, restaurants, and entertainment.",
    pricePerMonth: 1700,
    bedrooms: 2,
    bathrooms: 1,
    sizeSqft: 950,
    listedDate: "2024-12-02",
    details: {
      description:
        "Conveniently situated within walking distance of major attractions, this cozy condo features a chic design and all essential amenities.",
      detailImg: [
        "/images/details/urban_living_condo_1.jpg",
        "/images/details/urban_living_condo_2.jpg",
        "/images/details/urban_living_condo_3.jpg",
      ],
      thumbnails: [
        "/images/details/thumbnails/urban_living_condo_1.jpg",
        "/images/details/thumbnails/urban_living_condo_2.jpg",
        "/images/details/thumbnails/urban_living_condo_3.jpg",
      ],
      propertyDetails: [
        ["Unit ID", "AA123462"],
        ["Property Type", "Condo"],
        ["Property Size", 950],
        ["Rooms", 3],
        ["Bed Rooms", 2],
        ["Price", "$ 436,500.00 800/per sq ft"],
        ["Property Status", "rent"],
        ["Lot Size", 0],
        ["Bath Rooms", 1],
        ["Garages", 0],
      ],
      amenitiesFeatures: [
        "Elevator",
        "Security System",
        "Laundry Room",
        "WiFi",
        "Parking",
        "Garden",
      ],
      mapLocation: {
        latitude: 13.740708,
        longitude: 100.525,
      },
    },
  },
  {
    id: "AA123463",
    name: "Luxury Loft Condo",
    slug: "luxury-loft-condo",
    available: true,
    type: "sale",
    propertyImg: p8,
    shortDescription:
      "Stylish loft-style condo with high ceilings and luxury finishes.",
    pricePerMonth: 2600,
    bedrooms: 2,
    bathrooms: 2,
    sizeSqft: 1400,
    listedDate: "2024-12-03",
    details: {
      description:
        "This condo boasts modern aesthetics, large windows, and features that will impress at every turn. Ample living space with a contemporary vibe.",
      detailImg: [
        "/images/details/luxury_loft_condo_1.jpg",
        "/images/details/luxury_loft_condo_2.jpg",
        "/images/details/luxury_loft_condo_3.jpg",
      ],
      thumbnails: [
        "/images/details/thumbnails/luxury_loft_condo_1.jpg",
        "/images/details/thumbnails/luxury_loft_condo_2.jpg",
        "/images/details/thumbnails/luxury_loft_condo_3.jpg",
      ],
      propertyDetails: [
        ["Unit ID", "AA123463"],
        ["Property Type", "Condo"],
        ["Property Size", 1400],
        ["Rooms", 5],
        ["Bed Rooms", 2],
        ["Price", "$ 720,000.00 1200/per sq ft"],
        ["Property Status", "sale"],
        ["Lot Size", 0],
        ["Bath Rooms", 2],
        ["Garages", 1],
      ],
      amenitiesFeatures: [
        "Gym",
        "Rooftop Pool",
        "Pet Friendly",
        "Underground Parking",
        "WiFi",
        "Smart Home Features",
      ],
      mapLocation: {
        latitude: 13.750717,
        longitude: 100.53,
      },
    },
  },

  {
    id: "AA123464",
    name: "Pine Crest Condo",
    slug: "pine-crest-condo",
    available: true,
    type: "rent",
    propertyImg: p9,
    shortDescription:
      "Cozy condo nestled among pine trees, offering peace and serenity.",
    pricePerMonth: 1600,
    bedrooms: 2,
    bathrooms: 1,
    sizeSqft: 1100,
    listedDate: "2024-12-04",
    details: {
      description:
        "This charming condo is perfect for those who enjoy nature. It features rustic designs with modern conveniences, a perfect retreat.",
      detailImg: [
        "/images/details/pine_crest_condo_1.jpg",
        "/images/details/pine_crest_condo_2.jpg",
        "/images/details/pine_crest_condo_3.jpg",
      ],
      thumbnails: [
        "/images/details/thumbnails/pine_crest_condo_1.jpg",
        "/images/details/thumbnails/pine_crest_condo_2.jpg",
        "/images/details/thumbnails/pine_crest_condo_3.jpg",
      ],
      propertyDetails: [
        ["Unit ID", "AA123464"],
        ["Property Type", "Condo"],
        ["Property Size", 1100],
        ["Rooms", 4],
        ["Bed Rooms", 2],
        ["Price", "$ 485,000.00 900/per sq ft"],
        ["Property Status", "rent"],
        ["Lot Size", 0],
        ["Bath Rooms", 1],
        ["Garages", 1],
      ],
      amenitiesFeatures: [
        "Nature Trails",
        "Garden",
        "Parking",
        "Smoke Alarm",
        "WiFi",
      ],
      mapLocation: {
        latitude: 13.76,
        longitude: 100.55,
      },
    },
  },
  {
    id: "AA123465",
    name: "Riverside Condo",
    slug: "riverside-condo",
    available: true,
    type: "sale",
    propertyImg: p10,
    shortDescription:
      "Riverfront condo providing stunning views of the water and city skyline.",
    pricePerMonth: 2800,
    bedrooms: 3,
    bathrooms: 2,
    sizeSqft: 1650,
    listedDate: "2024-12-05",
    details: {
      description:
        "Live the waterfront lifestyle in this condo featuring large windows, contemporary design, and spacious living areas.",
      detailImg: [
        "/images/details/riverside_condo_1.jpg",
        "/images/details/riverside_condo_2.jpg",
        "/images/details/riverside_condo_3.jpg",
      ],
      thumbnails: [
        "/images/details/thumbnails/riverside_condo_1.jpg",
        "/images/details/thumbnails/riverside_condo_2.jpg",
        "/images/details/thumbnails/riverside_condo_3.jpg",
      ],
      propertyDetails: [
        ["Unit ID", "AA123465"],
        ["Property Type", "Condo"],
        ["Property Size", 1650],
        ["Rooms", 6],
        ["Bed Rooms", 3],
        ["Price", "$ 709,500.00 1200/per sq ft"],
        ["Property Status", "sale"],
        ["Lot Size", 0],
        ["Bath Rooms", 2],
        ["Garages", 2],
      ],
      amenitiesFeatures: [
        "Riverside Park",
        "Shared Pool",
        "Gym",
        "BBQ Area",
        "Parking",
        "Outdoor Seating",
      ],
      mapLocation: {
        latitude: 13.77,
        longitude: 100.53,
      },
    },
  },
];

const useCardList = create((set) => ({
  cards: [
    // {
    //   id: "AA123456",
    //   name: "Golden Pearl Condo",
    //   slug: "golden-pearl-condo",
    //   available: true,
    //   type: "rent",
    //   propertyImg: p1,
    //   shortDescription:
    //     "Prime condo located in downtown, just 10 minutes to the mall. Surrounded by lush parks, trendy cafes, and vibrant markets.",
    //   pricePerMonth: 1500,
    //   bedrooms: 2,
    //   bathrooms: 2,
    //   sizeSqft: 1200,
    //   listedDate: "2024-11-15",
    //   details: {
    //     description:
    //       "A beautifully designed condo with a modern layout, spacious living room, and fully equipped kitchen. Located in a prime downtown area with easy access to shopping centers and parks.",
    //     detailImg: [
    //       "/images/details/golden_pearl_condo_1.jpg",
    //       "/images/details/golden_pearl_condo_2.jpg",
    //       "/images/details/golden_pearl_condo_3.jpg",
    //     ],
    //     thumbnails: [
    //       "/images/details/thumbnails/golden_pearl_condo_1.jpg",
    //       "/images/details/thumbnails/golden_pearl_condo_2.jpg",
    //       "/images/details/thumbnails/golden_pearl_condo_3.jpg",
    //     ],
    //     propertyDetails: [
    //       ["Unit ID", "AA123456"],
    //       ["Property Type", "Condo"],
    //       ["Property Size", 1200],
    //       ["Rooms", 5],
    //       ["Bed Rooms", 2],
    //       ["Price", "$ 505,50000 1000/per sq ft"],
    //       ["Property Status", "rent"],
    //       ["Lot Size", 0],
    //       ["Bath Rooms", 2],
    //       ["Garages", 1],
    //     ],
    //     amenitiesFeatures: [
    //       "Smoke Alarm",
    //       "Gym",
    //       "Parking",
    //       "24th Security",
    //       "Garden",
    //       "Swimming Pool",
    //       "WiFi",
    //       "Mini Playground",
    //       "Convenience store",
    //       "Laundry Shop",
    //     ],
    //     mapLocation: {
    //       latitude: 13.736717,
    //       longitude: 100.523186,
    //     },
    //   },
    // },
    // {
    //   id: "BB987654",
    //   name: "Emerald View Condo",
    //   slug: "emerald-view-condo",
    //   available: true,
    //   type: "rent",
    //   propertyImg: p2,
    //   shortDescription:
    //     "Modern condo overlooking the river, located near public transportation hubs and schools.",
    //   pricePerMonth: 1800,
    //   bedrooms: 3,
    //   bathrooms: 2,
    //   sizeSqft: 1400,
    //   listedDate: "2024-11-20",
    //   details: {
    //     description:
    //       "Stylish condo with a scenic view of the river. Equipped with modern appliances and spacious bedrooms. Ideal for families.",
    //     detailImg: [
    //       "/images/details/emerald_view_condo_1.jpg",
    //       "/images/details/emerald_view_condo_2.jpg",
    //       "/images/details/emerald_view_condo_3.jpg",
    //     ],
    //     thumbnails: [
    //       "/images/details/thumbnails/emerald_view_condo_1.jpg",
    //       "/images/details/thumbnails/emerald_view_condo_2.jpg",
    //       "/images/details/thumbnails/emerald_view_condo_3.jpg",
    //     ],
    //     propertyDetails: [
    //       ["unitId", "BB987654"],
    //       ["propertyType", "Condo"],
    //       ["sizeSqft", 1400],
    //       ["rooms", 6],
    //       ["bedrooms", 3],
    //       ["price", "$ 600,00000 1500/per sq ft"],
    //       ["status", "Available"],
    //       ["lotSize", 0],
    //       ["bathrooms", 2],
    //       ["garages", 2],
    //     ],
    //     amenitiesFeatures: [
    //       "Smoke Alarm",
    //       "Gym",
    //       "River View",
    //       "Parking",
    //       "24th Security",
    //       "Swimming Pool",
    //       "WiFi",
    //       "Playground",
    //       "CCTV Monitoring",
    //       "Cafe",
    //     ],
    //     mapLocation: {
    //       latitude: 13.75633,
    //       longitude: 100.501765,
    //     },
    //   },
    // },
    ...condos,
    ...condos,
    ...condos,
    ...condos,
    ...condos,
    ...condos,
    ...condos,
    ...condos,
    ...condos,
  ],
  setCards: (cards) => set({ cards }),
  resetCards: () => set({ cards: [] }),
}));

export default useCardList;
